### ISSUE TITLE
Chinese translations bug

### ISSUE THREAD

**Issue by tobyliu415** [Jihadist/QModMaster#1]
1.  at modbusadapter.cpp :48

    m_modbus = modbus_new_rtu(port.toLatin1().constData(),baud,**parity.toLatin1()**,dataBits,stopBits,RTS);
    line = "Connecting to Serial Port [" + port + "]...";
    QLOG_TRACE() <<  line;

parity.toLatin1() is Chinese character "无"

**Comment by xakod** [comment]
Please post you issue directly to origin repo https://sourceforge.net/projects/qmodmaster/
